### ISSUE TITLE
Отображение и сортировка по ценам за кг/литр/шт

### ISSUE THREAD

**Issue by shtrih** [xob0t/MM-tools#1]
Например, яйца удобнее сортировать по цене за шт, т.к. предлагается упаковка разного размера: 6 шт, 10 шт, 30 шт.
Или молоко в упаковках 900 мл, 1л, 500 мл. Ну и любые другие весовые товары удобно сортировать по цене за кг в рамках категории.
У всех товаров, объём пишется в конце названия, легко парсится. 
Поскольку баллы начисляются в процентах, то этот процент можно учесть и для цены за кг/л/шт.

> ![image](https://github.com/xob0t/MM-tools/assets/544063/6c2c7ef8-c6a6-4dec-9117-e641848e0b9d)
> сортировка по выгоде до/после

**Comment by xob0t** [comment]
да, хорошая идея

**Comment by xob0t** [comment]
а, ну так это не ко мне, судя по скрину
https://github.com/undfndusr/mrp
